server:
  port: 8080

spring:
   datasource: 
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/chb?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8&useSSL=false
     
mybatis:
   mapper-locations: classpath:mappers/*.xml 
   type-aliases-package: com.jiufukameng.entity
    
tx:
   sms:
     appId: 1400172317
     appKey: 705169aa52fd97a797e7ef11aa4b449f
     templateId: 251768
     smsSign: 畅伙伴
     smsEffectiveTime: 5

     

     